name: 'Test'
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '23.7.0'
    - name: 'Install Deps'
      run: npm install
    - name: 'Test'
      run: npm run test
